language: python
python:
  - '2.7'
services:
    - docker
install:
    - docker build . -t ose3dprinter-test-i
    - docker run --name ose3dprinter-test --detach ose3dprinter-test-i
script:
    - docker exec -it ose3dprinter-test pytest --cov ose3dprinter_workbench/ test/
after_success:
    - coveralls
