language: python
python:
  - '2.7'
services:
    - docker
install:
    - docker build -f test.Dockerfile https://github.com/gbroques/ose-workbench-platform.git#master -t oseworkbench-test-image
    - docker run --name ose3dprinter-test --detach -v $(pwd):/var/app oseworkbench-test-image
script:
    - docker exec -it ose3dprinter-test pytest --cov ose3dprinter/app test/
after_success:
    - docker exec -e TRAVIS="$TRAVIS" -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" -e TRAVIS_PULL_REQUEST="$TRAVIS_PULL_REQUEST" ose3dprinter-test coveralls
