version: '3'
services:
  test:
    container_name: ose3dprinter-test
    image: ose3dprinter-test-i
    build: 
      context: ./
      dockerfile: test.Dockerfile
    volumes:
      -  ./:/var/app
    network_mode: bridge
  docs:
    container_name: ose3dprinter-docs
    image: ose3dprinter-docs-i
    build:
      context: ./
      dockerfile: docs.Dockerfile
    volumes:
      -  ./:/var/app
    network_mode: bridge
